baseURL = "https://yukkeorg.info/"
languageCode = "ja-jp"
title = "Yukke.org"

theme = "coder-portfolio"

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pygmentsUseClasses = true

disqusShortname = ""

[params]
  author = "Yukke.org"
  info = "プログラマー"
  description = ""
  keywords = "portfolio,developper"
  avatarurl = "images/my_avatar.png"

  footercontent = ""
  fixedbarContent = ""
  fixedbarContentAfter = ""

  hideCredits = true
  hideCopyright = true

  custom_css = []

  rtl = false

  snsShare = true
  enableTwitterShare = false
  enableFacebookShare = false
  enableHatenaShare = false
  enableLineShare = false
  enableLinkedInShare = false

  thumbnail = ""

  langseparator = "|"

[[params.social]]
  name = "GitHub"
  icon = "fab fa-github"
  weight = 1
  url = "https://github.com/yukkeorg"

[[menu.main]]
  name = "About"
  weight = 1
  url = "about"

